# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - galerierenovation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dotnet-wasm tool
        run: |
          dotnet workload install wasm-tools

      - name: dotnet-libman
        run: |
          cd GalerieRenovation.Web
          dotnet tool install Microsoft.Web.LibraryManager.Cli -g
          libman --version
          libman restore --verbosity detailed

      - name: Npm
        run: |
          cd GalerieRenovation.Web
          npm install jshint
          npm install grunt
          npm install grunt-cli
          npx -p sass@latest sass wwwroot/scss/galerie-renovation.scss:css/galerie-renovation.css --verbose
          npm install grunt-contrib-uglify --verbose
          npm install grunt-contrib-cssmin --verbose
          grunt cssmin --verbose
          grunt uglify --verbose
          cd ..

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/gr-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .gr-app
          path: ${{env.DOTNET_ROOT}}/gr-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .gr-app

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'galerierenovation'
      #     slot-name: 'Production'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A0F0E8A02EE24F66AEEA18F409F8749C }}
      #     package: .
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with: 
          azure_static_web_apps_api_token: ${{ secrets.GALERIE_RENOVATION_APITOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "GalerieRenovation.Web/wwwroot"
          output_location: "GalerieRenovation.Web/bin/Release/net6.0/publish/wwwroot" # Built app content directory - optional
